name = "adoracao-formoso"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "ADORACAO_KV"
id = "ADORACAO_KV_ID" # Substiua pelo ID gerado no painel do Cloudflare KV
